minimum_pre_commit_version: "3.5.0"
default_stages: [ pre-commit ]
default_language_version:
  python: python3.14
exclude: '^\.vale/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: end-of-file-fixer
      - id: check-vcs-permalinks
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: [ --maxkb=512 ]
      - id: check-yaml
      - id: check-toml
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-illegal-windows-names
      - id: forbid-submodules
#      - id: no-commit-to-branch
#      - id: check-json
#      - id: check-symlinks

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  # C++ CHECKS

#  - repo: https://github.com/pocc/pre-commit-hooks
#    rev: 0c2dfae267d798c9adff7b86976fa602aa0999b7
#    hooks:
#      - id: cppcheck
#        args:
#          - --enable=all
#          - --inline-suppr
#          - --suppressions-list=.cppcheck-suppressions
#          - --check-level=exhaustive
#          - --std=c++26
#          - --language=c++
#          - --error-exitcode=1
#          - -Iheaders
#          - '--template={file}:{line}:{column}: {severity}: {message} [{id}]'
#          - '--template-location={file}:{line}:{column}: note: {info}'
  #      - id: cpplint
  #        args: [-Iheaders]
  #        args: [ --style=file ]
  #      - id: clang-format
  #      - id: clang-tidy
  #      - id: oclint
  #      - id: uncrustify

  # CMake CHECKS

  - repo: https://github.com/BlankSpruce/gersemi-pre-commit
    rev: e98930bdc210d3387007f9252d8c1694ea7e410f  # 0.27.7
    hooks:
      - id: gersemi
        args: [ --indent, "2" ]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: e2c2116d86a80e72e7146a06e68b7c228afc6319  # v0.6.13
    hooks:
      - id: cmake-lint

  # SPELLING & GRAMMAR

  - repo: https://github.com/crate-ci/typos
    rev: bee27e3a4fd1ea2111cf90ab89cd076c870fce14  # v1.48.0
    hooks:
      - id: typos
        args: [ --force-exclude ]

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # v2.4.3
    hooks:
      - id: codespell
        additional_dependencies: [ tomli ]

  - repo: https://github.com/errata-ai/vale
    rev: 8c4ed0df90e45f93818ffed5ba587ff1e220a142  # v3.15.1
    hooks:
      - id: vale
        language_version: "1.25.7"

  # CONFIG FILE LINTING

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95  # v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 05c1426671b9237fb5e1444dd63aa5731bec0dfb  # v3.13.1-1
    hooks:
      - id: shfmt
        args: [ -i, "2", -sr, -bn, -ci ]

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # v1.7.12
    hooks:
      - id: actionlint
        language_version: "1.25.7"

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # v1.38.0
    hooks:
      - id: yamllint
        args: [ -c, .yamllint.yaml ]

  - repo: https://github.com/hukkin/mdformat
    rev: 82912cdaea4fb830f751504486a7879c70526547  # 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies: [ mdformat-gfm, mdformat-toc ]

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: ade0f95ddcf661c697d4670d2cfcbe95d0048a0a  # v0.9.3
    hooks:
      - id: taplo-format

  # VCS HYGIENE

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 6afcd8e9560ddf1b9a5032262a0be26540e85fb3  # v4.16.5
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ pre-push ]

  # SECURITY

  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e  # v8.30.1
    hooks:
      - id: gitleaks
        language_version: "1.25.7"

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 067260dc5fe6ea86b7551bfd6f8b3ba4e6c93129  # v1.28.0
    hooks:
      - id: zizmor

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 6b63472e72e1a91ed8a2f6d483790dfb644fa1d3  # 0.37.4
    hooks:
      - id: check-github-workflows
        args: [ "--verbose" ]
      - id: check-github-actions
      - id: check-dependabot

#  Todo: Wait for https://github.com/suzuki-shunsuke/pinact/pull/971 to be merged
#  - repo: https://github.com/suzuki-shunsuke/pinact
#    rev: v4.1.0
#    hooks:
#      - id: pinact
