minimum_pre_commit_version: "3.5.0"
default_stages: [ pre-commit ]
exclude: '^\.vale/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: [ --maxkb=512 ]
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: forbid-new-submodules
      - id: no-commit-to-branch

  #  - repo: https://github.com/pocc/pre-commit-hooks
  #    rev: 0c2dfae267d798c9adff7b86976fa602aa0999b7
  #    hooks:
  #      - id: clang-format
  #        args: [ --style=file ]
  #      - id: clang-tidy
  #      - id: oclint
  #      - id: uncrustify
  #      - id: cppcheck
  #        args:
  #          - --enable=all
  #          - --inline-suppr
  #          - --suppressions-list=.cppcheck-suppressions
  #          - --check-level=exhaustive
  #          - --std=c++26
  #          - --language=c++
  #          - --error-exitcode=1
  #          - -Iheaders
  #          - '--template={file}:{line}:{column}: {severity}: {message} [{id}]'
  #          - '--template-location={file}:{line}:{column}: note: {info}'
  #      - id: cpplint
  #      - id: include-what-you-use # No module support yet.
  #        args: [-Iheaders]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
        language_version: "1.25.7"

  - repo: https://github.com/BlankSpruce/gersemi-pre-commit
    rev: 0.27.7
    hooks:
      - id: gersemi
        args: [ --indent, "2" ]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-lint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        additional_dependencies: [ tomli ]
        exclude: ^.vale
        args:
          - --ignore-words-list=CreateOr,olt

  - repo: https://github.com/errata-ai/vale
    rev: v3.15.1
    hooks:
      - id: vale
        language_version: "1.25.7"

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        language_version: "1.25.7"

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [ -c, .yamllint.yaml ]

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies: [ mdformat-gfm, mdformat-toc ]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.5
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ pre-push ]

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.28.0
    hooks:
      - id: zizmor
