[project]
name = "spp"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
  "breathe>=4.36.0",
  "cpplint>=2.0.2",
  "furo>=2025.12.19",
  "myst-parser>=5.1.0",
  "ruff>=0.15.22",
  "sphinx>=9.1.0",
  "ty>=0.0.61",
]

[tool.typos.default.extend-words]
olt = "olt"
CreateMemCpy = "CreateMemCpy"

[tool.typos.files]
extend-exclude = ["Doxyfile", ".vale/**", "*.svg", "tests/gtest-parallel/**"]

[tool.codespell]
ignore-words-list = "CreateOr,CreateMemCpy,olt"
skip = "./.vale,./tests/gtest-parallel,*.svg"
