[project]
name = "spp"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
  "breathe>=4.36.0",
  "cpplint>=2.0.2",
  "furo>=2025.12.19",
  "myst-parser>=5.1.0",
  "ruff>=0.15.22",
  "sphinx>=9.1.0",
  "ty>=0.0.61",
]

[tool.ruff]
line-length = 120
extend-exclude = ["tests/gtest-parallel"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP", "B"]

[tool.typos.default.extend-words]
compex = "compex" # Compare exchange (atomics)
olt = "olt"       # Ordered less than
Cpy = "Cpy"       # Part of "MemCpy"

[tool.typos.files]
extend-exclude = ["Doxyfile", ".vale/**", "*.svg", "tests/gtest-parallel/**"]

[tool.codespell]
ignore-words-list = "CreateOr,CreateMemCpy,olt,compex"
skip = "./.vale,./tests/gtest-parallel,*.svg"
