# SonarQube (Cloud) project configuration file.

# Meta configuration.
sonar.projectKey=SamG101-Developer_spp
sonar.organization=samg101-developer

# Build configuration.
sonar.sources=sources,headers
sonar.tests=tests
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.sourceEncoding=UTF-8

# Ignore #undefs found in wrapper module files.
sonar.issue.ignore.multicriteria=modwrap
sonar.issue.ignore.multicriteria.modwrap.ruleKey=cpp:S959
sonar.issue.ignore.multicriteria.modwrap.resourceKey=**/headers/wrappers/**/*.ixx
