import collections
import difflib
import glob
import itertools
import re
import sys

# Generates the RTTI replacement used by Ast::Kind(), which lets "Ast::To<T>()" bypass most `dynamic_cast`s:
#  - ast_kind.ixx holds the AstKind enum.
#  - ast_kind_range.ixx holds the AstKindRange<T> traits, and the forward decls they need.
#
# One kind per concrete ast class, numbered so that every class's descendants occupy a contiguous block. That is what
# lets "Ast::To<T>()" answer with a range check instead of a "dynamic_cast": the hierarchy below "Ast" is a strict
# single-inheritance tree (no class has two ast bases), so a depth-first numbering has the property by construction.
#
# Two compile-time nets keep this in step with the headers: "Ast::Kind()" is pure virtual, so a new concrete class
# that does not pass its name to SPP_AST_KEY_FUNCTIONS stays abstract and fails to build; and passing a name that is
# not in the enum fails to build too. Neither can drift silently.

OUT_KIND = "headers/spp/asts/ast_kind.ixx"
OUT_RANGE = "headers/spp/asts/ast_kind_range.ixx"
CHECK = "--check" in sys.argv

# name -> {final, bases, file}
H = {}
pat = re.compile(
    r"SPP_EXP_CLS\s*(?:template\s*<[^>]*>\s*)?struct\s+spp::asts::(\w+)\s*(final)?\s*(?::\s*([^{]+))?\{", re.S
)
for f in sorted(glob.glob("headers/spp/asts/**/*.ixx", recursive=True)):
    for m in pat.finditer(open(f).read()):
        name = m.group(1)
        raw = m.group(3) or ""
        bases = [re.sub(r"^(public|private|protected)\s+", "", b.strip()).strip() for b in raw.split(",") if b.strip()]
        bases = [b.split("<")[0].replace("mixins::", "").strip() for b in bases]
        H[name] = dict(
            final=bool(m.group(2)),
            bases=bases,
            file=f,
            tmpl=bool(re.search(r"template\s*<", m.group(0).split("struct")[0])),
        )

names = set(H)
kids = collections.defaultdict(list)
roots = []
for n in H:
    ps = [b for b in H[n]["bases"] if b in names]
    (kids[ps[0]] if ps else roots).append(n)
for k in kids:
    kids[k].sort()

# Every class in the tree gets a kind, abstract ones included: "final" is not a reliable test of concreteness here
# (FunctionCallArgumentPositionalAst is concrete without it), and a kind no node ever returns costs nothing. Numbering
# a class before its descendants is what keeps each subtree contiguous.
order = []
rng = {}


def dfs(n):
    first = len(order)
    order.append(n)
    for c in kids[n]:
        dfs(c)
    rng[n] = (first, len(order) - 1)


dfs("Ast")

if not CHECK:
    detached = [r for r in roots if r != "Ast"]
    missing = [n for n in H if n not in rng and H[n]["final"]]
    print(f"concrete kinds: {len(order)}", file=sys.stderr)
    print(f"classes with a range: {len(rng)}", file=sys.stderr)
    print(f"detached (never reachable from Ast): {detached}", file=sys.stderr)
    print(f"concrete but unranked: {missing}", file=sys.stderr)

castable = {n for n in rng if not H[n]["tmpl"]}

fwd = "\n".join(f"  SPP_EXP_CLS struct {n};" for n in sorted(castable))
enum = "\n".join(f"  k{n}," for n in order)
traits = "\n\n".join(
    f"  template <>\n"
    f"  struct AstKindRange<{n}> {{\n"
    f"    static constexpr auto Known = true;\n"
    f"    static constexpr auto First = AstKind::k{order[a]};\n"
    f"    static constexpr auto Last = AstKind::k{order[b]};\n"
    f"  }};"
    for n, (a, b) in sorted(rng.items())
    if n in castable
)

kind_text = f"""module;
#include <spp/macros.hpp>

export module spp.asts.ast_kind;
import std;

// GENERATED by .tools/generate-ast-kinds.py - do not edit by hand, re-run it instead.

namespace spp::asts {{
  SPP_EXP_CLS enum class AstKind : std::uint8_t;
}}

SPP_EXP_CLS enum class spp::asts::AstKind : std::uint8_t {{
{enum}
}};
"""

range_text = f"""module;
#include <spp/macros.hpp>

export module spp.asts.ast_kind_range;
import spp.asts.ast_kind;

// GENERATED by .tools/generate-ast-kinds.py - do not edit by hand, re-run it instead.

namespace spp::asts {{
{fwd}
}}

namespace spp::asts {{
  SPP_EXP_CLS template <typename>
  struct AstKindRange {{
    static constexpr auto Known = false;
  }};

{traits}
}}
"""

outputs = {OUT_KIND: kind_text, OUT_RANGE: range_text}

if CHECK:
    stale = False
    for path, text in outputs.items():
        have = open(path).read()
        if have != text:
            diff = difflib.unified_diff(have.splitlines(True), text.splitlines(True), path, "generated", n=1)
            sys.stderr.writelines(itertools.islice(diff, 40))
            stale = True
    if stale:
        print("\nout of date - re-run: python3 .tools/generate-ast-kinds.py", file=sys.stderr)
        sys.exit(1)
    sys.exit(0)

for path, text in outputs.items():
    open(path, "w").write(text)
    print(f"wrote {path}", file=sys.stderr)
