module;
#include <spp/macros.hpp>

export module spp.asts.ast_kind;
import std;

// GENERATED by .tools/generate-ast-kinds.py - do not edit by hand, re-run it instead.
//
// One kind per concrete ast class, numbered so that every class's descendants occupy a contiguous block. That is what
// lets "Ast::To<T>()" answer with a range check instead of a "dynamic_cast": the hierarchy below "Ast" is a strict
// single-inheritance tree (no class has two ast bases), so a depth-first numbering has the property by construction.
//
// Two compile-time nets keep this in step with the headers: "Ast::Kind()" is pure virtual, so a new concrete class
// that does not pass its name to SPP_AST_KEY_FUNCTIONS stays abstract and fails to build; and passing a name that is
// not in this enum fails to build too. Neither can drift silently.

namespace spp::asts {
  SPP_EXP_CLS enum class AstKind : std::uint8_t;

  SPP_EXP_CLS struct AnnotationAst;
  SPP_EXP_CLS struct ArrayLiteralAst;
  SPP_EXP_CLS struct ArrayLiteralExplicitElementsAst;
  SPP_EXP_CLS struct ArrayLiteralRepeatedElementAst;
  SPP_EXP_CLS struct AssignmentStatementAst;
  SPP_EXP_CLS struct Ast;
  SPP_EXP_CLS struct BinaryExpressionAst;
  SPP_EXP_CLS struct BooleanLiteralAst;
  SPP_EXP_CLS struct CaseExpressionAst;
  SPP_EXP_CLS struct CaseExpressionBranchAst;
  SPP_EXP_CLS struct CasePatternVariantAst;
  SPP_EXP_CLS struct CasePatternVariantDestructureArrayAst;
  SPP_EXP_CLS struct CasePatternVariantDestructureAttributeBindingAst;
  SPP_EXP_CLS struct CasePatternVariantDestructureObjectAst;
  SPP_EXP_CLS struct CasePatternVariantDestructureSkipMultipleArgumentsAst;
  SPP_EXP_CLS struct CasePatternVariantDestructureSkipSingleArgumentAst;
  SPP_EXP_CLS struct CasePatternVariantDestructureTupleAst;
  SPP_EXP_CLS struct CasePatternVariantElseAst;
  SPP_EXP_CLS struct CasePatternVariantElseCaseAst;
  SPP_EXP_CLS struct CasePatternVariantExpressionAst;
  SPP_EXP_CLS struct CasePatternVariantLiteralAst;
  SPP_EXP_CLS struct CasePatternVariantSingleIdentifierAst;
  SPP_EXP_CLS struct CharLiteralAst;
  SPP_EXP_CLS struct ClassAttributeAst;
  SPP_EXP_CLS struct ClassImplementationAst;
  SPP_EXP_CLS struct ClassPrototypeAst;
  SPP_EXP_CLS struct ClosureExpressionAst;
  SPP_EXP_CLS struct ClosureExpressionCaptureAst;
  SPP_EXP_CLS struct ClosureExpressionCaptureGroupAst;
  SPP_EXP_CLS struct ClosureExpressionParameterAndCaptureGroupAst;
  SPP_EXP_CLS struct CmpStatementAst;
  SPP_EXP_CLS struct ConventionAst;
  SPP_EXP_CLS struct ConventionMutAst;
  SPP_EXP_CLS struct ConventionRefAst;
  SPP_EXP_CLS struct CoroutinePrototypeAst;
  SPP_EXP_CLS struct DeferStatementAst;
  SPP_EXP_CLS struct ExpressionAst;
  SPP_EXP_CLS struct FloatLiteralAst;
  SPP_EXP_CLS struct FoldExpressionAst;
  SPP_EXP_CLS struct FunctionCallArgumentAst;
  SPP_EXP_CLS struct FunctionCallArgumentGroupAst;
  SPP_EXP_CLS struct FunctionCallArgumentKeywordAst;
  SPP_EXP_CLS struct FunctionCallArgumentPositionalAst;
  SPP_EXP_CLS struct FunctionImplementationAst;
  SPP_EXP_CLS struct FunctionImplementationLoweredAst;
  SPP_EXP_CLS struct FunctionParameterAst;
  SPP_EXP_CLS struct FunctionParameterGroupAst;
  SPP_EXP_CLS struct FunctionParameterOptionalAst;
  SPP_EXP_CLS struct FunctionParameterRequiredAst;
  SPP_EXP_CLS struct FunctionParameterSelfAst;
  SPP_EXP_CLS struct FunctionParameterVariadicAst;
  SPP_EXP_CLS struct FunctionPrototypeAst;
  SPP_EXP_CLS struct GenExpressionAst;
  SPP_EXP_CLS struct GenWithExpressionAst;
  SPP_EXP_CLS struct GenericArgumentAst;
  SPP_EXP_CLS struct GenericArgumentCompAst;
  SPP_EXP_CLS struct GenericArgumentCompKeywordAst;
  SPP_EXP_CLS struct GenericArgumentCompPositionalAst;
  SPP_EXP_CLS struct GenericArgumentGroupAst;
  SPP_EXP_CLS struct GenericArgumentTypeAst;
  SPP_EXP_CLS struct GenericArgumentTypeKeywordAst;
  SPP_EXP_CLS struct GenericArgumentTypePositionalAst;
  SPP_EXP_CLS struct GenericParameterAst;
  SPP_EXP_CLS struct GenericParameterCompAst;
  SPP_EXP_CLS struct GenericParameterCompOptionalAst;
  SPP_EXP_CLS struct GenericParameterCompRequiredAst;
  SPP_EXP_CLS struct GenericParameterCompVariadicAst;
  SPP_EXP_CLS struct GenericParameterGroupAst;
  SPP_EXP_CLS struct GenericParameterTypeAst;
  SPP_EXP_CLS struct GenericParameterTypeInlineConstraintsAst;
  SPP_EXP_CLS struct GenericParameterTypeOptionalAst;
  SPP_EXP_CLS struct GenericParameterTypeRequiredAst;
  SPP_EXP_CLS struct GenericParameterTypeVariadicAst;
  SPP_EXP_CLS struct IdentifierAst;
  SPP_EXP_CLS struct InnerScopeExpressionAst;
  SPP_EXP_CLS struct IntegerLiteralAst;
  SPP_EXP_CLS struct IsExpressionAst;
  SPP_EXP_CLS struct LetStatementAst;
  SPP_EXP_CLS struct LetStatementInitializedAst;
  SPP_EXP_CLS struct LetStatementUninitializedAst;
  SPP_EXP_CLS struct LiteralAst;
  SPP_EXP_CLS struct LocalVariableAst;
  SPP_EXP_CLS struct LocalVariableDestructureArrayAst;
  SPP_EXP_CLS struct LocalVariableDestructureAttributeBindingAst;
  SPP_EXP_CLS struct LocalVariableDestructureObjectAst;
  SPP_EXP_CLS struct LocalVariableDestructureSkipMultipleArgumentsAst;
  SPP_EXP_CLS struct LocalVariableDestructureSkipSingleArgumentAst;
  SPP_EXP_CLS struct LocalVariableDestructureTupleAst;
  SPP_EXP_CLS struct LocalVariableSingleIdentifierAliasAst;
  SPP_EXP_CLS struct LocalVariableSingleIdentifierAst;
  SPP_EXP_CLS struct LoopConditionalExpressionAst;
  SPP_EXP_CLS struct LoopControlFlowStatementAst;
  SPP_EXP_CLS struct LoopElseStatementAst;
  SPP_EXP_CLS struct LoopExpressionAst;
  SPP_EXP_CLS struct LoopIterableExpressionAst;
  SPP_EXP_CLS struct ModuleImplementationAst;
  SPP_EXP_CLS struct ModulePrototypeAst;
  SPP_EXP_CLS struct ObjectInitializerArgumentAst;
  SPP_EXP_CLS struct ObjectInitializerArgumentGroupAst;
  SPP_EXP_CLS struct ObjectInitializerArgumentKeywordAst;
  SPP_EXP_CLS struct ObjectInitializerArgumentShorthandAst;
  SPP_EXP_CLS struct ObjectInitializerAst;
  SPP_EXP_CLS struct ParenthesisedExpressionAst;
  SPP_EXP_CLS struct PatternGuardAst;
  SPP_EXP_CLS struct PostfixExpressionAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorDerefAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorEarlyReturnAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorFunctionCallAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorIndexAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorKeywordNotAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorKeywordResAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorRuntimeMemberAccessAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorSliceAst;
  SPP_EXP_CLS struct PostfixExpressionOperatorStaticMemberAccessAst;
  SPP_EXP_CLS struct PrimaryExpressionAst;
  SPP_EXP_CLS struct RetStatementAst;
  SPP_EXP_CLS struct StatementAst;
  SPP_EXP_CLS struct StringLiteralAst;
  SPP_EXP_CLS struct SubroutinePrototypeAst;
  SPP_EXP_CLS struct SupImplementationAst;
  SPP_EXP_CLS struct SupPrototypeExtensionAst;
  SPP_EXP_CLS struct SupPrototypeFunctionsAst;
  SPP_EXP_CLS struct TokenAst;
  SPP_EXP_CLS struct TupleLiteralAst;
  SPP_EXP_CLS struct TypeArrayShorthandAst;
  SPP_EXP_CLS struct TypeAst;
  SPP_EXP_CLS struct TypeBinaryExpressionAst;
  SPP_EXP_CLS struct TypeIdentifierAst;
  SPP_EXP_CLS struct TypeParenthesisedExpressionAst;
  SPP_EXP_CLS struct TypePostfixExpressionAst;
  SPP_EXP_CLS struct TypePostfixExpressionOperatorAst;
  SPP_EXP_CLS struct TypePostfixExpressionOperatorNestedTypeAst;
  SPP_EXP_CLS struct TypeStatementAst;
  SPP_EXP_CLS struct TypeTupleShorthandAst;
  SPP_EXP_CLS struct TypeUnaryExpressionAst;
  SPP_EXP_CLS struct TypeUnaryExpressionOperatorAst;
  SPP_EXP_CLS struct TypeUnaryExpressionOperatorBorrowAst;
  SPP_EXP_CLS struct TypeUnaryExpressionOperatorNamespaceAst;
  SPP_EXP_CLS struct UnaryExpressionAst;
  SPP_EXP_CLS struct UnaryExpressionOperatorAst;
  SPP_EXP_CLS struct UnaryExpressionOperatorAsyncAst;
  SPP_EXP_CLS struct UseStatementAst;
  SPP_EXP_CLS struct UseStatementVariableAst;
}

SPP_EXP_CLS enum class spp::asts::AstKind : std::uint8_t {
  kAst,
  kAnnotationAst,
  kCaseExpressionBranchAst,
  kCasePatternVariantAst,
  kCasePatternVariantDestructureArrayAst,
  kCasePatternVariantDestructureAttributeBindingAst,
  kCasePatternVariantDestructureObjectAst,
  kCasePatternVariantDestructureSkipMultipleArgumentsAst,
  kCasePatternVariantDestructureSkipSingleArgumentAst,
  kCasePatternVariantDestructureTupleAst,
  kCasePatternVariantElseAst,
  kCasePatternVariantElseCaseAst,
  kCasePatternVariantExpressionAst,
  kCasePatternVariantLiteralAst,
  kCasePatternVariantSingleIdentifierAst,
  kClassAttributeAst,
  kClassPrototypeAst,
  kClosureExpressionCaptureGroupAst,
  kClosureExpressionParameterAndCaptureGroupAst,
  kConventionAst,
  kConventionMutAst,
  kConventionRefAst,
  kFunctionCallArgumentAst,
  kFunctionCallArgumentKeywordAst,
  kFunctionCallArgumentPositionalAst,
  kClosureExpressionCaptureAst,
  kFunctionCallArgumentGroupAst,
  kFunctionParameterAst,
  kFunctionParameterOptionalAst,
  kFunctionParameterRequiredAst,
  kFunctionParameterSelfAst,
  kFunctionParameterVariadicAst,
  kFunctionParameterGroupAst,
  kFunctionPrototypeAst,
  kCoroutinePrototypeAst,
  kSubroutinePrototypeAst,
  kGenericArgumentAst,
  kGenericArgumentCompAst,
  kGenericArgumentCompKeywordAst,
  kGenericArgumentCompPositionalAst,
  kGenericArgumentTypeAst,
  kGenericArgumentTypeKeywordAst,
  kGenericArgumentTypePositionalAst,
  kGenericArgumentGroupAst,
  kGenericParameterAst,
  kGenericParameterCompAst,
  kGenericParameterCompOptionalAst,
  kGenericParameterCompRequiredAst,
  kGenericParameterCompVariadicAst,
  kGenericParameterTypeAst,
  kGenericParameterTypeOptionalAst,
  kGenericParameterTypeRequiredAst,
  kGenericParameterTypeVariadicAst,
  kGenericParameterGroupAst,
  kGenericParameterTypeInlineConstraintsAst,
  kInnerScopeAst,
  kClassImplementationAst,
  kSupImplementationAst,
  kLocalVariableAst,
  kLocalVariableDestructureArrayAst,
  kLocalVariableDestructureAttributeBindingAst,
  kLocalVariableDestructureObjectAst,
  kLocalVariableDestructureSkipMultipleArgumentsAst,
  kLocalVariableDestructureSkipSingleArgumentAst,
  kLocalVariableDestructureTupleAst,
  kLocalVariableSingleIdentifierAst,
  kLocalVariableSingleIdentifierAliasAst,
  kLoopElseStatementAst,
  kModuleImplementationAst,
  kModulePrototypeAst,
  kObjectInitializerArgumentAst,
  kObjectInitializerArgumentKeywordAst,
  kObjectInitializerArgumentShorthandAst,
  kObjectInitializerArgumentGroupAst,
  kPatternGuardAst,
  kPostfixExpressionOperatorAst,
  kPostfixExpressionOperatorDerefAst,
  kPostfixExpressionOperatorEarlyReturnAst,
  kPostfixExpressionOperatorFunctionCallAst,
  kPostfixExpressionOperatorIndexAst,
  kPostfixExpressionOperatorKeywordNotAst,
  kPostfixExpressionOperatorKeywordResAst,
  kPostfixExpressionOperatorRuntimeMemberAccessAst,
  kPostfixExpressionOperatorSliceAst,
  kPostfixExpressionOperatorStaticMemberAccessAst,
  kStatementAst,
  kAssignmentStatementAst,
  kCmpStatementAst,
  kDeferStatementAst,
  kExpressionAst,
  kBinaryExpressionAst,
  kIsExpressionAst,
  kPostfixExpressionAst,
  kPrimaryExpressionAst,
  kCaseExpressionAst,
  kClosureExpressionAst,
  kFoldExpressionAst,
  kGenExpressionAst,
  kGenWithExpressionAst,
  kIdentifierAst,
  kInnerScopeExpressionAst,
  kFunctionImplementationAst,
  kFunctionImplementationLoweredAst,
  kLiteralAst,
  kArrayLiteralAst,
  kArrayLiteralExplicitElementsAst,
  kArrayLiteralRepeatedElementAst,
  kBooleanLiteralAst,
  kCharLiteralAst,
  kFloatLiteralAst,
  kIntegerLiteralAst,
  kStringLiteralAst,
  kTupleLiteralAst,
  kLoopExpressionAst,
  kLoopConditionalExpressionAst,
  kLoopIterableExpressionAst,
  kObjectInitializerAst,
  kParenthesisedExpressionAst,
  kTypeAst,
  kTypeIdentifierAst,
  kTypePostfixExpressionAst,
  kTypeUnaryExpressionAst,
  kUnaryExpressionAst,
  kLetStatementAst,
  kLetStatementInitializedAst,
  kLetStatementUninitializedAst,
  kLoopControlFlowStatementAst,
  kRetStatementAst,
  kTypeStatementAst,
  kUseStatementAst,
  kUseStatementVariableAst,
  kSupPrototypeExtensionAst,
  kSupPrototypeFunctionsAst,
  kTokenAst,
  kTypeArrayShorthandAst,
  kTypeBinaryExpressionAst,
  kTypeParenthesisedExpressionAst,
  kTypePostfixExpressionOperatorAst,
  kTypePostfixExpressionOperatorNestedTypeAst,
  kTypeTupleShorthandAst,
  kTypeUnaryExpressionOperatorAst,
  kTypeUnaryExpressionOperatorBorrowAst,
  kTypeUnaryExpressionOperatorNamespaceAst,
  kUnaryExpressionOperatorAst,
  kUnaryExpressionOperatorAsyncAst,
};

namespace spp::asts {
  /**
   * The block of kinds that are a @p T . Unspecialised for anything outside the ast tree - the mixins, which are
   * cross-casts rather than downcasts - and @c Ast::To() falls back to @c dynamic_cast for those.
   */
  SPP_EXP_CLS template <typename T>
  struct AstKindRange {
    static constexpr auto Known = false;
  };

  template <>
  struct AstKindRange<AnnotationAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kAnnotationAst;
    static constexpr auto Last = AstKind::kAnnotationAst;
  };

  template <>
  struct AstKindRange<ArrayLiteralAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kArrayLiteralAst;
    static constexpr auto Last = AstKind::kArrayLiteralRepeatedElementAst;
  };

  template <>
  struct AstKindRange<ArrayLiteralExplicitElementsAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kArrayLiteralExplicitElementsAst;
    static constexpr auto Last = AstKind::kArrayLiteralExplicitElementsAst;
  };

  template <>
  struct AstKindRange<ArrayLiteralRepeatedElementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kArrayLiteralRepeatedElementAst;
    static constexpr auto Last = AstKind::kArrayLiteralRepeatedElementAst;
  };

  template <>
  struct AstKindRange<AssignmentStatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kAssignmentStatementAst;
    static constexpr auto Last = AstKind::kAssignmentStatementAst;
  };

  template <>
  struct AstKindRange<Ast> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kAst;
    static constexpr auto Last = AstKind::kUnaryExpressionOperatorAsyncAst;
  };

  template <>
  struct AstKindRange<BinaryExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kBinaryExpressionAst;
    static constexpr auto Last = AstKind::kBinaryExpressionAst;
  };

  template <>
  struct AstKindRange<BooleanLiteralAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kBooleanLiteralAst;
    static constexpr auto Last = AstKind::kBooleanLiteralAst;
  };

  template <>
  struct AstKindRange<CaseExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCaseExpressionAst;
    static constexpr auto Last = AstKind::kCaseExpressionAst;
  };

  template <>
  struct AstKindRange<CaseExpressionBranchAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCaseExpressionBranchAst;
    static constexpr auto Last = AstKind::kCaseExpressionBranchAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantAst;
    static constexpr auto Last = AstKind::kCasePatternVariantSingleIdentifierAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantDestructureArrayAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantDestructureArrayAst;
    static constexpr auto Last = AstKind::kCasePatternVariantDestructureArrayAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantDestructureAttributeBindingAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantDestructureAttributeBindingAst;
    static constexpr auto Last = AstKind::kCasePatternVariantDestructureAttributeBindingAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantDestructureObjectAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantDestructureObjectAst;
    static constexpr auto Last = AstKind::kCasePatternVariantDestructureObjectAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantDestructureSkipMultipleArgumentsAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantDestructureSkipMultipleArgumentsAst;
    static constexpr auto Last = AstKind::kCasePatternVariantDestructureSkipMultipleArgumentsAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantDestructureSkipSingleArgumentAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantDestructureSkipSingleArgumentAst;
    static constexpr auto Last = AstKind::kCasePatternVariantDestructureSkipSingleArgumentAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantDestructureTupleAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantDestructureTupleAst;
    static constexpr auto Last = AstKind::kCasePatternVariantDestructureTupleAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantElseAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantElseAst;
    static constexpr auto Last = AstKind::kCasePatternVariantElseAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantElseCaseAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantElseCaseAst;
    static constexpr auto Last = AstKind::kCasePatternVariantElseCaseAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantExpressionAst;
    static constexpr auto Last = AstKind::kCasePatternVariantExpressionAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantLiteralAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantLiteralAst;
    static constexpr auto Last = AstKind::kCasePatternVariantLiteralAst;
  };

  template <>
  struct AstKindRange<CasePatternVariantSingleIdentifierAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCasePatternVariantSingleIdentifierAst;
    static constexpr auto Last = AstKind::kCasePatternVariantSingleIdentifierAst;
  };

  template <>
  struct AstKindRange<CharLiteralAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCharLiteralAst;
    static constexpr auto Last = AstKind::kCharLiteralAst;
  };

  template <>
  struct AstKindRange<ClassAttributeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kClassAttributeAst;
    static constexpr auto Last = AstKind::kClassAttributeAst;
  };

  template <>
  struct AstKindRange<ClassImplementationAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kClassImplementationAst;
    static constexpr auto Last = AstKind::kClassImplementationAst;
  };

  template <>
  struct AstKindRange<ClassPrototypeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kClassPrototypeAst;
    static constexpr auto Last = AstKind::kClassPrototypeAst;
  };

  template <>
  struct AstKindRange<ClosureExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kClosureExpressionAst;
    static constexpr auto Last = AstKind::kClosureExpressionAst;
  };

  template <>
  struct AstKindRange<ClosureExpressionCaptureAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kClosureExpressionCaptureAst;
    static constexpr auto Last = AstKind::kClosureExpressionCaptureAst;
  };

  template <>
  struct AstKindRange<ClosureExpressionCaptureGroupAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kClosureExpressionCaptureGroupAst;
    static constexpr auto Last = AstKind::kClosureExpressionCaptureGroupAst;
  };

  template <>
  struct AstKindRange<ClosureExpressionParameterAndCaptureGroupAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kClosureExpressionParameterAndCaptureGroupAst;
    static constexpr auto Last = AstKind::kClosureExpressionParameterAndCaptureGroupAst;
  };

  template <>
  struct AstKindRange<CmpStatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCmpStatementAst;
    static constexpr auto Last = AstKind::kCmpStatementAst;
  };

  template <>
  struct AstKindRange<ConventionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kConventionAst;
    static constexpr auto Last = AstKind::kConventionRefAst;
  };

  template <>
  struct AstKindRange<ConventionMutAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kConventionMutAst;
    static constexpr auto Last = AstKind::kConventionMutAst;
  };

  template <>
  struct AstKindRange<ConventionRefAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kConventionRefAst;
    static constexpr auto Last = AstKind::kConventionRefAst;
  };

  template <>
  struct AstKindRange<CoroutinePrototypeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kCoroutinePrototypeAst;
    static constexpr auto Last = AstKind::kCoroutinePrototypeAst;
  };

  template <>
  struct AstKindRange<DeferStatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kDeferStatementAst;
    static constexpr auto Last = AstKind::kDeferStatementAst;
  };

  template <>
  struct AstKindRange<ExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kExpressionAst;
    static constexpr auto Last = AstKind::kUnaryExpressionAst;
  };

  template <>
  struct AstKindRange<FloatLiteralAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFloatLiteralAst;
    static constexpr auto Last = AstKind::kFloatLiteralAst;
  };

  template <>
  struct AstKindRange<FoldExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFoldExpressionAst;
    static constexpr auto Last = AstKind::kFoldExpressionAst;
  };

  template <>
  struct AstKindRange<FunctionCallArgumentAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionCallArgumentAst;
    static constexpr auto Last = AstKind::kClosureExpressionCaptureAst;
  };

  template <>
  struct AstKindRange<FunctionCallArgumentGroupAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionCallArgumentGroupAst;
    static constexpr auto Last = AstKind::kFunctionCallArgumentGroupAst;
  };

  template <>
  struct AstKindRange<FunctionCallArgumentKeywordAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionCallArgumentKeywordAst;
    static constexpr auto Last = AstKind::kFunctionCallArgumentKeywordAst;
  };

  template <>
  struct AstKindRange<FunctionCallArgumentPositionalAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionCallArgumentPositionalAst;
    static constexpr auto Last = AstKind::kClosureExpressionCaptureAst;
  };

  template <>
  struct AstKindRange<FunctionImplementationAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionImplementationAst;
    static constexpr auto Last = AstKind::kFunctionImplementationLoweredAst;
  };

  template <>
  struct AstKindRange<FunctionImplementationLoweredAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionImplementationLoweredAst;
    static constexpr auto Last = AstKind::kFunctionImplementationLoweredAst;
  };

  template <>
  struct AstKindRange<FunctionParameterAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionParameterAst;
    static constexpr auto Last = AstKind::kFunctionParameterVariadicAst;
  };

  template <>
  struct AstKindRange<FunctionParameterGroupAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionParameterGroupAst;
    static constexpr auto Last = AstKind::kFunctionParameterGroupAst;
  };

  template <>
  struct AstKindRange<FunctionParameterOptionalAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionParameterOptionalAst;
    static constexpr auto Last = AstKind::kFunctionParameterOptionalAst;
  };

  template <>
  struct AstKindRange<FunctionParameterRequiredAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionParameterRequiredAst;
    static constexpr auto Last = AstKind::kFunctionParameterRequiredAst;
  };

  template <>
  struct AstKindRange<FunctionParameterSelfAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionParameterSelfAst;
    static constexpr auto Last = AstKind::kFunctionParameterSelfAst;
  };

  template <>
  struct AstKindRange<FunctionParameterVariadicAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionParameterVariadicAst;
    static constexpr auto Last = AstKind::kFunctionParameterVariadicAst;
  };

  template <>
  struct AstKindRange<FunctionPrototypeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kFunctionPrototypeAst;
    static constexpr auto Last = AstKind::kSubroutinePrototypeAst;
  };

  template <>
  struct AstKindRange<GenExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenExpressionAst;
    static constexpr auto Last = AstKind::kGenExpressionAst;
  };

  template <>
  struct AstKindRange<GenWithExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenWithExpressionAst;
    static constexpr auto Last = AstKind::kGenWithExpressionAst;
  };

  template <>
  struct AstKindRange<GenericArgumentAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericArgumentAst;
    static constexpr auto Last = AstKind::kGenericArgumentTypePositionalAst;
  };

  template <>
  struct AstKindRange<GenericArgumentCompAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericArgumentCompAst;
    static constexpr auto Last = AstKind::kGenericArgumentCompPositionalAst;
  };

  template <>
  struct AstKindRange<GenericArgumentCompKeywordAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericArgumentCompKeywordAst;
    static constexpr auto Last = AstKind::kGenericArgumentCompKeywordAst;
  };

  template <>
  struct AstKindRange<GenericArgumentCompPositionalAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericArgumentCompPositionalAst;
    static constexpr auto Last = AstKind::kGenericArgumentCompPositionalAst;
  };

  template <>
  struct AstKindRange<GenericArgumentGroupAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericArgumentGroupAst;
    static constexpr auto Last = AstKind::kGenericArgumentGroupAst;
  };

  template <>
  struct AstKindRange<GenericArgumentTypeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericArgumentTypeAst;
    static constexpr auto Last = AstKind::kGenericArgumentTypePositionalAst;
  };

  template <>
  struct AstKindRange<GenericArgumentTypeKeywordAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericArgumentTypeKeywordAst;
    static constexpr auto Last = AstKind::kGenericArgumentTypeKeywordAst;
  };

  template <>
  struct AstKindRange<GenericArgumentTypePositionalAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericArgumentTypePositionalAst;
    static constexpr auto Last = AstKind::kGenericArgumentTypePositionalAst;
  };

  template <>
  struct AstKindRange<GenericParameterAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterAst;
    static constexpr auto Last = AstKind::kGenericParameterTypeVariadicAst;
  };

  template <>
  struct AstKindRange<GenericParameterCompAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterCompAst;
    static constexpr auto Last = AstKind::kGenericParameterCompVariadicAst;
  };

  template <>
  struct AstKindRange<GenericParameterCompOptionalAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterCompOptionalAst;
    static constexpr auto Last = AstKind::kGenericParameterCompOptionalAst;
  };

  template <>
  struct AstKindRange<GenericParameterCompRequiredAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterCompRequiredAst;
    static constexpr auto Last = AstKind::kGenericParameterCompRequiredAst;
  };

  template <>
  struct AstKindRange<GenericParameterCompVariadicAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterCompVariadicAst;
    static constexpr auto Last = AstKind::kGenericParameterCompVariadicAst;
  };

  template <>
  struct AstKindRange<GenericParameterGroupAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterGroupAst;
    static constexpr auto Last = AstKind::kGenericParameterGroupAst;
  };

  template <>
  struct AstKindRange<GenericParameterTypeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterTypeAst;
    static constexpr auto Last = AstKind::kGenericParameterTypeVariadicAst;
  };

  template <>
  struct AstKindRange<GenericParameterTypeInlineConstraintsAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterTypeInlineConstraintsAst;
    static constexpr auto Last = AstKind::kGenericParameterTypeInlineConstraintsAst;
  };

  template <>
  struct AstKindRange<GenericParameterTypeOptionalAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterTypeOptionalAst;
    static constexpr auto Last = AstKind::kGenericParameterTypeOptionalAst;
  };

  template <>
  struct AstKindRange<GenericParameterTypeRequiredAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterTypeRequiredAst;
    static constexpr auto Last = AstKind::kGenericParameterTypeRequiredAst;
  };

  template <>
  struct AstKindRange<GenericParameterTypeVariadicAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kGenericParameterTypeVariadicAst;
    static constexpr auto Last = AstKind::kGenericParameterTypeVariadicAst;
  };

  template <>
  struct AstKindRange<IdentifierAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kIdentifierAst;
    static constexpr auto Last = AstKind::kIdentifierAst;
  };

  template <>
  struct AstKindRange<InnerScopeExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kInnerScopeExpressionAst;
    static constexpr auto Last = AstKind::kFunctionImplementationLoweredAst;
  };

  template <>
  struct AstKindRange<IntegerLiteralAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kIntegerLiteralAst;
    static constexpr auto Last = AstKind::kIntegerLiteralAst;
  };

  template <>
  struct AstKindRange<IsExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kIsExpressionAst;
    static constexpr auto Last = AstKind::kIsExpressionAst;
  };

  template <>
  struct AstKindRange<LetStatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLetStatementAst;
    static constexpr auto Last = AstKind::kLetStatementUninitializedAst;
  };

  template <>
  struct AstKindRange<LetStatementInitializedAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLetStatementInitializedAst;
    static constexpr auto Last = AstKind::kLetStatementInitializedAst;
  };

  template <>
  struct AstKindRange<LetStatementUninitializedAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLetStatementUninitializedAst;
    static constexpr auto Last = AstKind::kLetStatementUninitializedAst;
  };

  template <>
  struct AstKindRange<LiteralAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLiteralAst;
    static constexpr auto Last = AstKind::kTupleLiteralAst;
  };

  template <>
  struct AstKindRange<LocalVariableAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLocalVariableAst;
    static constexpr auto Last = AstKind::kLocalVariableSingleIdentifierAst;
  };

  template <>
  struct AstKindRange<LocalVariableDestructureArrayAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLocalVariableDestructureArrayAst;
    static constexpr auto Last = AstKind::kLocalVariableDestructureArrayAst;
  };

  template <>
  struct AstKindRange<LocalVariableDestructureAttributeBindingAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLocalVariableDestructureAttributeBindingAst;
    static constexpr auto Last = AstKind::kLocalVariableDestructureAttributeBindingAst;
  };

  template <>
  struct AstKindRange<LocalVariableDestructureObjectAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLocalVariableDestructureObjectAst;
    static constexpr auto Last = AstKind::kLocalVariableDestructureObjectAst;
  };

  template <>
  struct AstKindRange<LocalVariableDestructureSkipMultipleArgumentsAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLocalVariableDestructureSkipMultipleArgumentsAst;
    static constexpr auto Last = AstKind::kLocalVariableDestructureSkipMultipleArgumentsAst;
  };

  template <>
  struct AstKindRange<LocalVariableDestructureSkipSingleArgumentAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLocalVariableDestructureSkipSingleArgumentAst;
    static constexpr auto Last = AstKind::kLocalVariableDestructureSkipSingleArgumentAst;
  };

  template <>
  struct AstKindRange<LocalVariableDestructureTupleAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLocalVariableDestructureTupleAst;
    static constexpr auto Last = AstKind::kLocalVariableDestructureTupleAst;
  };

  template <>
  struct AstKindRange<LocalVariableSingleIdentifierAliasAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLocalVariableSingleIdentifierAliasAst;
    static constexpr auto Last = AstKind::kLocalVariableSingleIdentifierAliasAst;
  };

  template <>
  struct AstKindRange<LocalVariableSingleIdentifierAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLocalVariableSingleIdentifierAst;
    static constexpr auto Last = AstKind::kLocalVariableSingleIdentifierAst;
  };

  template <>
  struct AstKindRange<LoopConditionalExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLoopConditionalExpressionAst;
    static constexpr auto Last = AstKind::kLoopConditionalExpressionAst;
  };

  template <>
  struct AstKindRange<LoopControlFlowStatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLoopControlFlowStatementAst;
    static constexpr auto Last = AstKind::kLoopControlFlowStatementAst;
  };

  template <>
  struct AstKindRange<LoopElseStatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLoopElseStatementAst;
    static constexpr auto Last = AstKind::kLoopElseStatementAst;
  };

  template <>
  struct AstKindRange<LoopExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLoopExpressionAst;
    static constexpr auto Last = AstKind::kLoopIterableExpressionAst;
  };

  template <>
  struct AstKindRange<LoopIterableExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kLoopIterableExpressionAst;
    static constexpr auto Last = AstKind::kLoopIterableExpressionAst;
  };

  template <>
  struct AstKindRange<ModuleImplementationAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kModuleImplementationAst;
    static constexpr auto Last = AstKind::kModuleImplementationAst;
  };

  template <>
  struct AstKindRange<ModulePrototypeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kModulePrototypeAst;
    static constexpr auto Last = AstKind::kModulePrototypeAst;
  };

  template <>
  struct AstKindRange<ObjectInitializerArgumentAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kObjectInitializerArgumentAst;
    static constexpr auto Last = AstKind::kObjectInitializerArgumentShorthandAst;
  };

  template <>
  struct AstKindRange<ObjectInitializerArgumentGroupAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kObjectInitializerArgumentGroupAst;
    static constexpr auto Last = AstKind::kObjectInitializerArgumentGroupAst;
  };

  template <>
  struct AstKindRange<ObjectInitializerArgumentKeywordAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kObjectInitializerArgumentKeywordAst;
    static constexpr auto Last = AstKind::kObjectInitializerArgumentKeywordAst;
  };

  template <>
  struct AstKindRange<ObjectInitializerArgumentShorthandAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kObjectInitializerArgumentShorthandAst;
    static constexpr auto Last = AstKind::kObjectInitializerArgumentShorthandAst;
  };

  template <>
  struct AstKindRange<ObjectInitializerAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kObjectInitializerAst;
    static constexpr auto Last = AstKind::kObjectInitializerAst;
  };

  template <>
  struct AstKindRange<ParenthesisedExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kParenthesisedExpressionAst;
    static constexpr auto Last = AstKind::kParenthesisedExpressionAst;
  };

  template <>
  struct AstKindRange<PatternGuardAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPatternGuardAst;
    static constexpr auto Last = AstKind::kPatternGuardAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionAst;
    static constexpr auto Last = AstKind::kPostfixExpressionAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorStaticMemberAccessAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorDerefAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorDerefAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorDerefAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorEarlyReturnAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorEarlyReturnAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorEarlyReturnAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorFunctionCallAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorFunctionCallAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorFunctionCallAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorIndexAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorIndexAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorIndexAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorKeywordNotAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorKeywordNotAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorKeywordNotAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorKeywordResAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorKeywordResAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorKeywordResAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorRuntimeMemberAccessAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorRuntimeMemberAccessAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorRuntimeMemberAccessAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorSliceAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorSliceAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorSliceAst;
  };

  template <>
  struct AstKindRange<PostfixExpressionOperatorStaticMemberAccessAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPostfixExpressionOperatorStaticMemberAccessAst;
    static constexpr auto Last = AstKind::kPostfixExpressionOperatorStaticMemberAccessAst;
  };

  template <>
  struct AstKindRange<PrimaryExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kPrimaryExpressionAst;
    static constexpr auto Last = AstKind::kTypeUnaryExpressionAst;
  };

  template <>
  struct AstKindRange<RetStatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kRetStatementAst;
    static constexpr auto Last = AstKind::kRetStatementAst;
  };

  template <>
  struct AstKindRange<StatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kStatementAst;
    static constexpr auto Last = AstKind::kUseStatementVariableAst;
  };

  template <>
  struct AstKindRange<StringLiteralAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kStringLiteralAst;
    static constexpr auto Last = AstKind::kStringLiteralAst;
  };

  template <>
  struct AstKindRange<SubroutinePrototypeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kSubroutinePrototypeAst;
    static constexpr auto Last = AstKind::kSubroutinePrototypeAst;
  };

  template <>
  struct AstKindRange<SupImplementationAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kSupImplementationAst;
    static constexpr auto Last = AstKind::kSupImplementationAst;
  };

  template <>
  struct AstKindRange<SupPrototypeExtensionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kSupPrototypeExtensionAst;
    static constexpr auto Last = AstKind::kSupPrototypeExtensionAst;
  };

  template <>
  struct AstKindRange<SupPrototypeFunctionsAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kSupPrototypeFunctionsAst;
    static constexpr auto Last = AstKind::kSupPrototypeFunctionsAst;
  };

  template <>
  struct AstKindRange<TokenAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTokenAst;
    static constexpr auto Last = AstKind::kTokenAst;
  };

  template <>
  struct AstKindRange<TupleLiteralAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTupleLiteralAst;
    static constexpr auto Last = AstKind::kTupleLiteralAst;
  };

  template <>
  struct AstKindRange<TypeArrayShorthandAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeArrayShorthandAst;
    static constexpr auto Last = AstKind::kTypeArrayShorthandAst;
  };

  template <>
  struct AstKindRange<TypeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeAst;
    static constexpr auto Last = AstKind::kTypeUnaryExpressionAst;
  };

  template <>
  struct AstKindRange<TypeBinaryExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeBinaryExpressionAst;
    static constexpr auto Last = AstKind::kTypeBinaryExpressionAst;
  };

  template <>
  struct AstKindRange<TypeIdentifierAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeIdentifierAst;
    static constexpr auto Last = AstKind::kTypeIdentifierAst;
  };

  template <>
  struct AstKindRange<TypeParenthesisedExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeParenthesisedExpressionAst;
    static constexpr auto Last = AstKind::kTypeParenthesisedExpressionAst;
  };

  template <>
  struct AstKindRange<TypePostfixExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypePostfixExpressionAst;
    static constexpr auto Last = AstKind::kTypePostfixExpressionAst;
  };

  template <>
  struct AstKindRange<TypePostfixExpressionOperatorAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypePostfixExpressionOperatorAst;
    static constexpr auto Last = AstKind::kTypePostfixExpressionOperatorNestedTypeAst;
  };

  template <>
  struct AstKindRange<TypePostfixExpressionOperatorNestedTypeAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypePostfixExpressionOperatorNestedTypeAst;
    static constexpr auto Last = AstKind::kTypePostfixExpressionOperatorNestedTypeAst;
  };

  template <>
  struct AstKindRange<TypeStatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeStatementAst;
    static constexpr auto Last = AstKind::kTypeStatementAst;
  };

  template <>
  struct AstKindRange<TypeTupleShorthandAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeTupleShorthandAst;
    static constexpr auto Last = AstKind::kTypeTupleShorthandAst;
  };

  template <>
  struct AstKindRange<TypeUnaryExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeUnaryExpressionAst;
    static constexpr auto Last = AstKind::kTypeUnaryExpressionAst;
  };

  template <>
  struct AstKindRange<TypeUnaryExpressionOperatorAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeUnaryExpressionOperatorAst;
    static constexpr auto Last = AstKind::kTypeUnaryExpressionOperatorNamespaceAst;
  };

  template <>
  struct AstKindRange<TypeUnaryExpressionOperatorBorrowAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeUnaryExpressionOperatorBorrowAst;
    static constexpr auto Last = AstKind::kTypeUnaryExpressionOperatorBorrowAst;
  };

  template <>
  struct AstKindRange<TypeUnaryExpressionOperatorNamespaceAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kTypeUnaryExpressionOperatorNamespaceAst;
    static constexpr auto Last = AstKind::kTypeUnaryExpressionOperatorNamespaceAst;
  };

  template <>
  struct AstKindRange<UnaryExpressionAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kUnaryExpressionAst;
    static constexpr auto Last = AstKind::kUnaryExpressionAst;
  };

  template <>
  struct AstKindRange<UnaryExpressionOperatorAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kUnaryExpressionOperatorAst;
    static constexpr auto Last = AstKind::kUnaryExpressionOperatorAsyncAst;
  };

  template <>
  struct AstKindRange<UnaryExpressionOperatorAsyncAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kUnaryExpressionOperatorAsyncAst;
    static constexpr auto Last = AstKind::kUnaryExpressionOperatorAsyncAst;
  };

  template <>
  struct AstKindRange<UseStatementAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kUseStatementAst;
    static constexpr auto Last = AstKind::kUseStatementAst;
  };

  template <>
  struct AstKindRange<UseStatementVariableAst> {
    static constexpr auto Known = true;
    static constexpr auto First = AstKind::kUseStatementVariableAst;
    static constexpr auto Last = AstKind::kUseStatementVariableAst;
  };
}
