module;
#include <spp/macros.hpp>

export module spp.asts.function_call_argument_ast;
import spp.asts.ast;
import spp.asts.mixins.orderable_ast;
import spp.asts.mixins.type_inferrable_ast;
import spp.asts.utils.orderable;
import spp.codegen.llvm_ctx;
import spp.utils.types;
import llvm;
import std;

namespace spp::asts {
    SPP_EXP_CLS struct ConventionAst;
    SPP_EXP_CLS struct ExpressionAst;
    SPP_EXP_CLS struct FunctionCallArgumentAst;
    SPP_EXP_CLS struct PostfixExpressionOperatorFunctionCallAst;
    SPP_EXP_CLS struct TypeAst;
}

COMMON_AST_IMPORTS

/**
 * The FunctionCallArgumentAst is the base class representing an argument in a function call. It is inherited into the
 * "positional" and "keyword" variants.
 */
SPP_EXP_CLS struct spp::asts::FunctionCallArgumentAst : Ast, mixins::OrderableAst, mixins::TypeInferrableAst {
    /**
     * Use the base Ast's constructors.
     */
    using Ast::Ast;

    /**
     * The convention on the argument being passed into the function call. Conventions are applicable to both positional
     * and keyword arguments.
     */
    Unique<ConventionAst> Conv;

    /**
     * The expression that is being passed as the argument to the function call. Both positional and keyword arguments
     * have a value.
     */
    Unique<ExpressionAst> Val;

    /**
     * Construct the FunctionCallArgumentAst with the arguments matching the members.
     * @param conv The convention on the argument being passed into the function call.
     * @param val The expression that is being passed as the argument to the function call.
     * @param order_tag The order tag for this argument, used to enforce ordering rules.
     */
    FunctionCallArgumentAst(
        decltype(Conv) &&conv,
        decltype(Val) &&val,
        utils::OrderableTag order_tag);

    auto Stage7_AnalyseSemantics(analyse::scopes::ScopeManager *sm, meta::CompilerMetaData *meta) -> void override;

    auto Stage8_CheckMemory(analyse::scopes::ScopeManager *sm, meta::CompilerMetaData *meta) -> void override;

    auto Stage9_CompTimeResolve(analyse::scopes::ScopeManager *sm, meta::CompilerMetaData *meta) -> void override;

    auto Stage11_CodeGen(analyse::scopes::ScopeManager *sm, meta::CompilerMetaData *meta, codegen::LLvmCtx *ctx) -> llvm::Value* override;

    auto InferType(analyse::scopes::ScopeManager *sm, meta::CompilerMetaData *meta) -> TypeAst* override;

    auto SetSelfType(Unique<TypeAst> self_type) -> void;

    auto GetSelfType() const -> TypeAst*;

private:
    /**
     * When an argument is generated by the compiler for the "self" type being injected into a method call, the type is
     * passed explicitly to speed up inference.
     */
    Unique<TypeAst> _InjectedSelfType;
};
