module;
#include <spp/macros.hpp>

export module spp.asts.function_call_argument_ast;
import spp.asts.ast;
import spp.asts.mixins.orderable_ast;
import spp.asts.mixins.type_inferrable_ast;
import spp.asts.utils.orderable;
import spp.codegen.llvm_ctx;
import llvm;
import std;

namespace spp::asts {
    SPP_EXP_CLS struct ConventionAst;
    SPP_EXP_CLS struct ExpressionAst;
    SPP_EXP_CLS struct FunctionCallArgumentAst;
    SPP_EXP_CLS struct PostfixExpressionOperatorFunctionCallAst;
    SPP_EXP_CLS struct TypeAst;
}


/**
 * The FunctionCallArgumentAst is the base class representing an argument in a function call. It is inherited into the
 * "positional" and "keyword" variants.
 */
SPP_EXP_CLS struct spp::asts::FunctionCallArgumentAst :
    virtual Ast,
    mixins::OrderableAst,
    mixins::TypeInferrableAst {
    /**
     * Use the base Ast's constructors.
     */
    using Ast::Ast;

    /**
     * When an argument is generated by the compiler for the "self" type being injected into a method call, the type is
     * passed explicitly to speed up inference.
     */
    std::shared_ptr<TypeAst> injected_self_type;

    /**
     * The convention on the argument being passed into the function call. Conventions are applicable to both positional
     * and keyword arguments.
     */
    std::unique_ptr<ConventionAst> conv;

    /**
     * The expression that is being passed as the argument to the function call. Both positional and keyword arguments
     * have a value.
     */
    std::unique_ptr<ExpressionAst> val;

    /**
     * Construct the FunctionCallArgumentAst with the arguments matching the members.
     * @param conv The convention on the argument being passed into the function call.
     * @param val The expression that is being passed as the argument to the function call.
     * @param order_tag The order tag for this argument, used to enforce ordering rules.
     */
    FunctionCallArgumentAst(
        decltype(conv) &&conv,
        decltype(val) &&val,
        utils::OrderableTag order_tag);

    auto set_self_type(std::shared_ptr<TypeAst> self_type) -> void;

    auto get_self_type() -> std::shared_ptr<TypeAst>;

    auto stage_7_analyse_semantics(ScopeManager *sm, CompilerMetaData *meta) -> void override;

    auto stage_8_check_memory(ScopeManager *sm, CompilerMetaData *meta) -> void override;

    auto stage_9_comptime_resolution(ScopeManager *sm, CompilerMetaData *meta) -> void override;

    auto stage_11_code_gen_2(ScopeManager *sm, CompilerMetaData *meta, codegen::LLvmCtx *ctx) -> llvm::Value* override;

    auto infer_type(ScopeManager *sm, CompilerMetaData *meta) -> std::shared_ptr<TypeAst> override;
};
