module;
#include <spp/macros.hpp>
#include <spp/analyse/macros.hpp>

module spp.asts.case_pattern_variant_destructure_object_ast;
import spp.analyse.errors.semantic_error;
import spp.analyse.errors.semantic_error_builder;
import spp.analyse.scopes.scope;
import spp.analyse.scopes.scope_manager;
import spp.analyse.scopes.symbols;
import spp.analyse.utils.case_utils;
import spp.analyse.utils.mem_info_utils;
import spp.analyse.utils.mem_utils;
import spp.analyse.utils.type_compare;
import spp.analyse.utils.type_predicates;
import spp.asts.ast;
import spp.asts.boolean_literal_ast;
import spp.asts.case_pattern_variant_destructure_attribute_binding_ast;
import spp.asts.case_pattern_variant_literal_ast;
import spp.asts.convention_ref_ast;
import spp.asts.expression_ast;
import spp.asts.fold_expression_ast;
import spp.asts.function_call_argument_group_ast;
import spp.asts.function_call_argument_positional_ast;
import spp.asts.generic_argument_group_ast;
import spp.asts.identifier_ast;
import spp.asts.let_statement_initialized_ast;
import spp.asts.literal_ast;
import spp.asts.local_variable_destructure_object_ast;
import spp.asts.local_variable_single_identifier_alias_ast;
import spp.asts.local_variable_single_identifier_ast;
import spp.asts.postfix_expression_ast;
import spp.asts.postfix_expression_operator_deref_ast;
import spp.asts.postfix_expression_operator_function_call_ast;
import spp.asts.postfix_expression_operator_runtime_member_access_ast;
import spp.asts.token_ast;
import spp.asts.type_ast;
import spp.asts.type_identifier_ast;
import spp.asts.meta.compiler_meta_data;
import spp.asts.utils.ast_utils;
import spp.codegen.llvm_sym_info;
import spp.codegen.llvm_type;
import spp.lex.tokens;
import spp.utils.uid;
import genex;

SPP_MOD_BEGIN
spp::asts::CasePatternVariantDestructureObjectAst::CasePatternVariantDestructureObjectAst(
  decltype(Type) type,
  decltype(TokL) &&tok_l,
  decltype(Elems) &&elems,
  decltype(TokR) &&tok_r) :
  Type(std::move(type)),
  TokL(std::move(tok_l)),
  Elems(std::move(elems)),
  TokR(std::move(tok_r)),
  _CondSym(nullptr),
  _FlowSym(nullptr) {
  SPP_SET_AST_TO_DEFAULT_IF_NULLPTR(this->TokL, lex::SppTokenType::TK_LEFT_PARENTHESIS, "(");
  SPP_SET_AST_TO_DEFAULT_IF_NULLPTR(this->TokR, lex::SppTokenType::TK_RIGHT_PARENTHESIS, ")");
  Source.OriginalType = AstClone(Type);
}

spp::asts::CasePatternVariantDestructureObjectAst::~CasePatternVariantDestructureObjectAst() = default;

auto spp::asts::CasePatternVariantDestructureObjectAst::FromType(
  Shared<TypeAst> const &type)
  -> Unique<CasePatternVariantDestructureObjectAst> {
  auto empty_elems = Vec<Unique<CasePatternVariantAst>>{};
  return MakeUnique<CasePatternVariantDestructureObjectAst>(type, nullptr, std::move(empty_elems), nullptr);
}

auto spp::asts::CasePatternVariantDestructureObjectAst::PosStart() const
  -> std::size_t {
  // Use the "[" token.
  return Source.OriginalType->PosStart();
}

auto spp::asts::CasePatternVariantDestructureObjectAst::PosEnd() const
  -> std::size_t {
  // Use the "]" token.
  return TokR->PosEnd();
}

auto spp::asts::CasePatternVariantDestructureObjectAst::Clone() const
  -> Unique<Ast> {
  // Clone all the members of the ast.
  auto c = MakeUnique<CasePatternVariantDestructureObjectAst>(
    AstClone(Type),
    AstClone(TokL),
    AstCloneVec(Elems),
    AstClone(TokR));
  c->_MappedLet = AstClone(_MappedLet);
  return c;
}

auto spp::asts::CasePatternVariantDestructureObjectAst::ToString() const
  -> Str {
  SPP_STRING_START;
  SPP_STRING_APPEND(Type);
  SPP_STRING_APPEND(TokL);
  SPP_STRING_EXTEND(Elems, ", ");
  SPP_STRING_APPEND(TokR);
  SPP_STRING_END;
}

auto spp::asts::CasePatternVariantDestructureObjectAst::Stage7_AnalyseSemantics(
  ScopeManager *sm,
  CompilerMetaData *meta)
  -> void {
  using analyse::utils::case_utils::CreateAndAnalysePatternEqFuncsDummyCore;
  using analyse::utils::type_predicates::IsTypeVariant;
  using analyse::utils::type_compare::TypeEq;
  using analyse::errors::SppTypeMismatchError;

  auto conv = AstClone(Type->GetConvention());
  Type->Stage7_AnalyseSemantics(sm, meta);
  Type = sm->CurrentScope->GetTypeSymbol(Type.get())->FqName();
  Type = Type->WithConvention(std::move(conv));

  // Flow-type the case condition (when it is a simple identifier) so that both the eq-check expressions generated by
  // CreateAndAnalysePatternEqFuncs* and the member-access bindings inside _MappedLet resolve against the narrowed
  // variant type (Pass[T] rather than the outer declared type Res[T,E] for example).
  const auto cond_as_id = meta->CaseCondition->To<IdentifierAst>();
  auto *const cond_sym = cond_as_id != nullptr ? sm->CurrentScope->GetVarSymbol(cond_as_id) : nullptr;
  _CondSym = cond_sym != nullptr ? cond_sym->SharedFromThis<analyse::scopes::VariableSymbol>() : nullptr;
  if (_CondSym != nullptr and IsTypeVariant(*_CondSym->Type, *sm->CurrentScope)) {
    RaiseIf<SppTypeMismatchError>(
      not TypeEq(*_CondSym->Type, *Type, *sm->CurrentScope, *sm->CurrentScope),
      {sm->CurrentScope}, ERR_ARGS(*meta->CaseCondition, *_CondSym->Type, *Source.OriginalType, *Type));
    _FlowSym = MakeShared<analyse::scopes::VariableSymbol>(*_CondSym);
    _FlowSym->LlvmInfo = _CondSym->LlvmInfo;

    // What this narrows, so that consuming through the
    // narrowed name discharges the value itself.
    _FlowSym->NarrowsSym = _CondSym;
    _FlowSym->Type = Type;
    _FlowSym->IsFlowNarrowing = true;

    if (Type->GetConvention() != nullptr) {
      const auto borrow_scope = spp::get<1>(_CondSym->MemInfo->AstBorrowed) ? : _CondSym->ScopeDefinedIn;
      _FlowSym->MemInfo->AstBorrowed = {Type.get(), borrow_scope};
    }
    sm->CurrentScope->AddVarSymbol(_FlowSym);
  }

  auto var = ConvToVar(meta);
  _MappedLet = MakeUnique<LetStatementInitializedAst>(
    nullptr, std::move(var), nullptr, nullptr, AstClone(meta->CaseCondition));
  _MappedLet->Stage7_AnalyseSemantics(sm, meta);

  CreateAndAnalysePatternEqFuncsDummyCore(
    Elems | genex::views::ptr | genex::to<Vec>(), sm, meta);
}

auto spp::asts::CasePatternVariantDestructureObjectAst::Stage8_CheckMemory(
  ScopeManager *sm,
  CompilerMetaData *meta)
  -> void {
  if (_FlowSym != nullptr and _CondSym != nullptr) {
    _FlowSym->MemInfo->FillFromSnapshot(_CondSym->MemInfo->Snapshot());
  }

  // Forward memory checking to the mapped let statement.
  _MappedLet->Stage8_CheckMemory(sm, meta);
}

auto spp::asts::CasePatternVariantDestructureObjectAst::Stage9_CompTimeResolve(
  ScopeManager *sm,
  CompilerMetaData *meta)
  -> void {
  //
  using analyse::utils::case_utils::CreateAndAnalysePatternEqCompTime;

  // TODO: Do a non-variant type comparison first.
  // TODO: Do not allow if the condition type is variant.
  // Transform the pattern into comptime values; all need to be true.
  auto comptime_transforms = CreateAndAnalysePatternEqCompTime(
    Elems | genex::views::ptr | genex::to<Vec>(), sm, meta);

  // All must be true for the pattern to match (look for any false).
  const auto all_true = genex::all_of(
    comptime_transforms,
    [](auto const &x) { return x->template To<BooleanLiteralAst>()->IsTrue(); });

  // Generate the "let" statement to introduce all the symbols.
  _MappedLet->Stage9_CompTimeResolve(sm, meta);

  // Based on the result, return the corresponding comptime value.
  const auto p = PosStart();
  meta->CmpResult = all_true ? BooleanLiteralAst::True(p) : BooleanLiteralAst::False(p);
}

auto spp::asts::CasePatternVariantDestructureObjectAst::Stage11_CodeGen(
  ScopeManager *sm,
  CompilerMetaData *meta,
  codegen::LlvmCtx *ctx)
  -> llvm::Value* {
  //
  using analyse::utils::case_utils::CreateAndAnalysePatternEqFuncsLlvm;

  // A flow symbol only exists for a variant condition, whose
  // members live behind the discriminant, so the narrowed
  // bindings index from the payload buffer rather than from
  // the variant's base address.
  const auto uid = "." + spp::utils::Uid(this);
  auto llvm_tag_check = static_cast<llvm::Value*>(nullptr);
  if (_FlowSym and _CondSym) {
    SPP_ASSERT(_CondSym->LlvmInfo->Alloca != nullptr);
    const auto llvm_variant_ty = sm->CurrentScope->GetTypeSymbol(
      _CondSym->Type.get())->LlvmInfo->LlvmType;
    SPP_ASSERT(llvm_variant_ty != nullptr);

    // Find the index in the variant's member types, of the
    // member type being flowed into. A variant can hold a borrow
    // as a member in its own right ("&S32 or None", which is what
    // resuming a "Gen[&S32]" gives), and then the convention is
    // part of what identifies the member rather than something
    // attached to the pattern, so the exact type is tried first.
    auto tag = codegen::GetVariantIndexOfMember(
      *_CondSym->Type, *Type, *sm->CurrentScope);
    if (not tag.has_value()) {
      tag = codegen::GetVariantIndexOfMember(
        *_CondSym->Type, *Type->WithoutConvention(), *sm->CurrentScope);
    }
    SPP_ASSERT(tag.has_value());

    // Next, get the actual tag value from the variant that is
    // telling us which member type is active in the variant.
    auto variant_ptr = _CondSym->LlvmInfo->Alloca;
    if (_CondSym->Type->GetConvention() != nullptr) {
      variant_ptr = ctx->Builder.CreateLoad(
        llvm::PointerType::get(*ctx->Context, 0), variant_ptr, "case.pattern.subject" + uid);
    }

    const auto llvm_tag = codegen::LoadVariantTag(
      variant_ptr, llvm_variant_ty, "case.pattern.tag" + uid, ctx);

    // Comparing the discriminant is what decides whether this
    // pattern matches.
    llvm_tag_check = ctx->Builder.CreateICmpEQ(
      llvm_tag, llvm::ConstantInt::get(codegen::GetVariantTagType(ctx), *tag),
      "case.pattern.is" + uid);

    // Set the alloca into the flow symbol (more precisely typed).
    // The flow symbol shares the condition symbol's llvm info up
    // to this point, so it is given its own here: writing the
    // payload address through the shared info would narrow the
    // condition symbol itself onto the payload for the remainder
    // of the enclosing function.
    _FlowSym->LlvmInfo = MakeShared<codegen::LlvmVarSymInfo>();
    _FlowSym->LlvmInfo->Alloca = codegen::GetVariantPayloadPtr(
      _CondSym->LlvmInfo->Alloca, llvm_variant_ty,
      "case.pattern.payload" + uid, ctx);
  }

  // A condition that is not a plain identifier has no symbol to
  // flow-type - "self@" is a deref, not a name - but its
  // discriminant still has to be checked.
  else if (meta->CaseCondition != nullptr and meta->LlvmCaseCondition != nullptr) {
    using analyse::utils::type_predicates::IsTypeVariant;
    const auto cond_type = meta->CaseCondition->InferType(sm, meta);
    const auto bare_cond_type = cond_type != nullptr ? cond_type->WithoutConvention() : nullptr;

    if (bare_cond_type != nullptr and IsTypeVariant(*bare_cond_type, *sm->CurrentScope)) {
      auto tag = codegen::GetVariantIndexOfMember(*bare_cond_type, *Type, *sm->CurrentScope);
      if (not tag.has_value()) {
        tag = codegen::GetVariantIndexOfMember(
          *bare_cond_type, *Type->WithoutConvention(), *sm->CurrentScope);
      }

      // The condition was generated once by the enclosing "case",
      // so it is read rather than rebuilt: it may be the variant
      // value itself, or a pointer to it when the condition was
      // reached through a borrow.
      const auto llvm_variant_ty = sm->CurrentScope->GetTypeSymbol(
        bare_cond_type.get())->LlvmInfo->LlvmType;

      auto llvm_tag = static_cast<llvm::Value*>(nullptr);
      if (tag.has_value() and meta->LlvmCaseCondition->getType()->isPointerTy()) {
        llvm_tag = codegen::LoadVariantTag(
          meta->LlvmCaseCondition, llvm_variant_ty, "case.pattern.tag" + uid, ctx);
      }
      else if (tag.has_value() and meta->LlvmCaseCondition->getType() == llvm_variant_ty) {
        llvm_tag = ctx->Builder.CreateExtractValue(
          meta->LlvmCaseCondition, 0, "case.pattern.tag" + uid);
      }

      if (llvm_tag != nullptr and llvm_tag->getType() == codegen::GetVariantTagType(ctx)) {
        llvm_tag_check = ctx->Builder.CreateICmpEQ(
          llvm_tag, llvm::ConstantInt::get(codegen::GetVariantTagType(ctx), *tag),
          "case.pattern.is" + uid);
      }
    }
  }

  // Run the codegen on the transformed "let" ast to introduce symbols into the llvm function.
  if (_MappedLet != nullptr) {
    _MappedLet->Stage11_CodeGen(sm, meta, ctx);
  }

  // Combine all the generated transforms into a single "AND"ed
  // expression.
  auto llvm_transforms = CreateAndAnalysePatternEqFuncsLlvm(
    Elems | genex::views::ptr | genex::to<Vec>(), sm, meta, ctx);

  const auto AND = [&ctx](auto a, auto b) { return ctx->Builder.CreateAnd(a, b); };
  auto llvm_master_transform = llvm_transforms.IsEmpty()
    ? llvm::cast<llvm::Value>(llvm::ConstantInt::getTrue(*ctx->Context))
    : genex::fold_left_first(llvm_transforms, std::move(AND));

  // Combine the potential variant check, should it exist, into
  // the type check. Place the tag check first (short-circuits on
  // the type check and prevents bad value comparisons).
  if (llvm_tag_check != nullptr) {
    llvm_master_transform = ctx->Builder.CreateAnd(
      llvm_tag_check, llvm_master_transform, "case.pattern.match" + uid);
  }

  return llvm_master_transform;
}

auto spp::asts::CasePatternVariantDestructureObjectAst::ConvToVar(
  CompilerMetaData *meta)
  -> Unique<LocalVariableAst> {
  // Recursively map the elements to their local variable counterparts.
  auto mapped_elems = Elems
    | genex::views::transform([meta](auto const &x) { return x->ConvToVar(meta); })
    | genex::to<Vec>();

  // Create the final local variable wrapping, tag it and return it.
  auto var = MakeUnique<LocalVariableDestructureObjectAst>(
    AstCloneShared(Type), nullptr, std::move(mapped_elems), nullptr);
  var->MarkFromCasePattern();
  return var;
}

SPP_MOD_END
